### PR TITLE
Added option to use KNITRO for NLPs

### PR DESCRIPTION
**Pull request by stelmo**
Very small change to the `_SUPPORTED_SOLVERS` that allows KNITRO to be used. Tested on my system and it works, did not add a specific test for it though...

### CODE REVIEW

**Review by odow — COMMENTED** [review]
Nice!

Seems they added some more solvers since I first wrote this:
image

Looks like we should be able to add Octeract and SNOPT as well.

**Review by odow — APPROVED** [review]

**Comment by odow** [comment]
Note to my future self:
```Julia
julia> s = NEOSServer.Server("");

julia> filter(x -> endswith(x, ":NL"), neos_listAllSolvers(s))
21-element Vector{Any}:
 "lp:COPT:NL"
 "milp:COPT:NL"
 "milp:OCTERACT:NL"
 "lp:OCTERACT:NL"
 "nco:Knitro:NL"
 "socp:Gurobi:NL"
 "socp:CPLEX:NL"
 "lp:CPLEX:NL"
 "milp:CPLEX:NL"
 "lp:Gurobi:NL"
 "milp:Gurobi:NL"
 "lp:FICO-Xpress:NL"
 "milp:FICO-Xpress:NL"
 "socp:FICO-Xpress:NL"
 "lp:MOSEK:NL"
 "milp:MOSEK:NL"
 "nco:SNOPT:NL"
 "minco:OCTERACT:NL"
 "go:OCTERACT:NL"
 "nco:OCTERACT:NL"
 "nco:Ipopt:NL"
```

**Comment by odow** [comment]
Thanks @stelmo! I'll tag a new release.

**Comment by stelmo** [comment]
If you are busy I can go ahead and add these solvers?

**Comment by odow** [comment]
I think we should be able to use them all now. (Let me know if that's not the case.)

I think NEOS just categorizes solvers to aid users. It doesn't prevent you from sending the "wrong" problem type. So it doesn't matter if you send OCTERACT a `minco`, `go` or `nco` for example.

**Pull request merged**
