### PR TITLE
WIP: Redo almost everything

### PR DESCRIPTION
**Pull request by odow**

### CODE REVIEW

**Comment by mlubin** [comment]
Woah, cool stuff!
@IainNZ @tkelman

**Comment by odow** [comment]
I've been messing around with the best way to structure things. Still a few things to sort out. Passing options and stuff. But I haven't really had the time to work on this recently...

Any thoughts/comments/suggestions?

**Comment by tkelman** [comment]
It's been so long since I last used NEOS, I had forgotten how useful this could totally be. I also just sat next to Hans Mittelmann on my connecting flight back from ISMP, that was fun.

**Comment by odow** [comment]
Its a bit of a pain having to parse each solver separately. Using AMPL display commands would be simpler.

**Comment by IainNZ** [comment]
Thats quite a diff :+1:

**Comment by mlubin** [comment]
Let us know if you'd like this to become a JuliaOpt project, seems like a good candidate.

**Comment by odow** [comment]
Having this under JuliaOpt is probably a good idea. I have no preference as to when this happens. It is probably usable in its current state. But I'm sure it breaks easily

**Comment by mlubin** [comment]
Typically we ask you to register the package in METADATA before we move it over to JuliaOpt.

**Pull request merged**
